<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 24/08/2018
 * Time: 7:02 AM
 */

function COIN_POT_TOKENS(){
    echo"
    <iframe scrolling=\"no\" frameborder=\"0\" src=\"https://coinpot.co/mine/coinpottokens/?ref=2A20F50D2AA9&mode=widget\" style=\"overflow:hidden;width:324px;height:470px;\"></iframe>
    ";
}

function bit_coin_core(){
    echo"
    <iframe scrolling=\"no\" frameborder=\"0\" src=\"https://coinpot.co/mine/bitcoin/?ref=2A20F50D2AA9&mode=widget\" style=\"overflow:hidden;width:324px;height:470px;\"></iframe>
    ";
}

function BIT_COIN_CASH(){
    echo"
    <iframe scrolling=\"no\" frameborder=\"0\" src=\"https://coinpot.co/mine/bitcoincash/?ref=2A20F50D2AA9&mode=widget\" style=\"overflow:hidden;width:324px;height:470px;\"></iframe>
    ";
}

function DOG_E_COIN(){
    echo"
    <iframe scrolling=\"no\" frameborder=\"0\" src=\"https://coinpot.co/mine/dogecoin/?ref=2A20F50D2AA9&mode=widget\" style=\"overflow:hidden;width:324px;height:470px;\"></iframe>
    ";
}

function LITE_COIN(){
    echo"
    <iframe scrolling=\"no\" frameborder=\"0\" src=\"https://coinpot.co/mine/litecoin/?ref=2A20F50D2AA9&mode=widget\" style=\"overflow:hidden;width:324px;height:470px;\"></iframe>
    ";
}

function DASH(){
    echo"
    <iframe scrolling=\"no\" frameborder=\"0\" src=\"https://coinpot.co/mine/dash/?ref=2A20F50D2AA9&mode=widget\" style=\"overflow:hidden;width:324px;height:470px;\"></iframe>
    ";
}