<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 24/08/2018
 * Time: 7:02 AM
 */
$ref = REF_TOKEN;

function COIN_POT_TOKENS($ref){
    echo"
    <iframe scrolling='no' frameborder='0' src='https://coinpot.co/mine/coinpottokens/?ref={$ref}&mode=widget' style='overflow:hidden;width:324px;height:470px;'></iframe>
    ";
}

function BIT_COIN_CORE($ref){
    echo"
    <iframe scrolling='no' frameborder='0' src='https://coinpot.co/mine/bitcoin/?ref={$ref}&mode=widget' style='overflow:hidden;width:324px;height:470px;'></iframe>
    ";
}

function BIT_COIN_CASH($ref){
    echo"
    <iframe scrolling='no' frameborder='0' src='https://coinpot.co/mine/bitcoincash/?ref={$ref}&mode=widget' style='overflow:hidden;width:324px;height:470px;'></iframe>
    ";
}

function DOG_E_COIN($ref){
    echo"
    <iframe scrolling='no' frameborder='0' src='https://coinpot.co/mine/dogecoin/?ref={$ref}&mode=widget' style='overflow:hidden;width:324px;height:470px;'></iframe>
    ";
}

function LITE_COIN($ref){
    echo"
    <iframe scrolling='no' frameborder='0' src='https://coinpot.co/mine/litecoin/?ref={$ref}&mode=widget' style='overflow:hidden;width:324px;height:470px;'></iframe>
    ";
}

function DASH($ref){
    echo"
    <iframe scrolling='no' frameborder='0' src='https://coinpot.co/mine/dash/?ref={$ref}&mode=widget' style='overflow:hidden;width:324px;height:470px;'></iframe>
    ";
}